latest:
  id: joha
panels:
- joha
- code_thoughts
#below may be separate file at some point
projects:
  joha:
    name: Joha
    proj_url: http://www.joha.us
    git_url: https://github.com/forforf/joha_grapher
  code_thoughts:
    name: Code Thoughts
    proj_url: http://forforf.github.com/code_thoughts/
    git_url: https://github.com/forforf/code_thoughts
